Use true and false as Use_ExtData2G settings in setCommonRunSettings.sh
Signed-off-by: Lizzie Lundgren <elundgren@seas.harvard.edu>

diff --git a/run/GCHP/setCommonRunSettings.sh.template b/run/GCHP/setCommonRunSettings.sh.template
--- a/run/GCHP/setCommonRunSettings.sh.template
+++ b/run/GCHP/setCommonRunSettings.sh.template
@@ -399,9 +399,9 @@ Model_Phase=FORWARD
 #------------------------------------------------
 #   MAPL ExtData versions
 #------------------------------------------------
-# Set to 2G to use ExtData2G; else will use legacy ExtData
+# Set to true to use ExtData2G in MAPL (requires yaml input file)
 
-ExtData_version=
+Use_ExtData2G=false
 
 
 ###############################
@@ -701,14 +701,15 @@ replace_val NY            ${NY}                 GCHP.rc
 replace_val CoresPerNode  ${NUM_CORES_PER_NODE} HISTORY.rc
 
 ###  Set which version of ExtData will be used
-if [[ ${ExtData_version} == "2G" ]]; then
-    replace_val USE_EXTDATA2G  .TRUE.  CAP.rc
+if [[ ${Use_ExtData2G} == "true" ]]; then
+    replace_val USE_EXTDATA2G  .TRUE.   CAP.rc
     replace_val USE_EXTDATA2G  .true.   GCHP.rc
-    # NOTE: updates needs to be made in this script to all places that
-    # edit ExtData.rc... extdata.yaml needs to be added.
-else
+elif [[ ${Use_ExtData2G} == "false" ]]; then
     replace_val USE_EXTDATA2G  .FALSE. CAP.rc
     replace_val USE_EXTDATA2G  .false. GCHP.rc
+else
+    echo "ERROR: Use_ExtData2G in setCommonRunSettings.sh must be either true or false."
+    exit 1
 fi
 
 ###  Make sure adjoint diagnostics (if present) are commented out if using
